package com.acmeflix.domain.enumeration;

public enum Genre {
    ACTION,ANIME,AWARD_WINNING,CHILDREN_FAMILY,CLASSIC,COMEDIES,CRIME,DOCUMENTARIES,DRAMAS,EUROPEAN,FANTASY,
    HOLIDAYS,HORROR,INDEPENDENT,MUSIC_MUSICALS,ROMANCE,SCI_FI,SHORTS,SPORTS,STAND_UP_COMEDY,THRILLER
}
